name: Release

on:
  workflow_dispatch

env:
  OCAML_DEFAULT_VERSION: 5.0.0
  OPAMYES: true

jobs:
  dune_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          fetch-tags: true

      - name: Use OCaml ${{ env.OCAML_DEFAULT_VERSION }}
        uses: ocaml/setup-ocaml@v2
        with:
          allow-prerelease-opam: true
          ocaml-compiler: ${{ env.OCAML_DEFAULT_VERSION }}
          dune-cache: true

      - name: Install dependencies
        run: opam exec -- make deps

      - name: Install dune-release
        run: opam install dune-release

      - name: Build the distribution archive
        run: opam exec -- dune-release distrib

      - name: Upload the artefact
        uses: actions/upload-artifact@v3
        with:
          name: alt-ergo-${{github.sha}}.tbz
          path: _build/alt-ergo-*.tbz
